<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('Movies').' V3')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/movies.css')
                        ->prependStylesheet($this->basePath() . '/css/zf-table/style.css')
                        ->prependStylesheet($this->basePath() . '/css/zf-table/zf-table.css')
                        ->prependStylesheet($this->basePath() . '/js/jquery-ui-1.11.1/jquery-ui.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css'); ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/bootstrap-confirmation.js')
            ->prependFile($this->basePath() . '/js/bootstrap.js')
            ->prependFile($this->basePath() . '/js/jquery.dataTables.min.js')
            ->prependFile($this->basePath() . '/js/zf-table.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/jquery-ui-1.11.1/jquery-ui.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js'); ?>
    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('movies', array('lang' => $this->moviesLanguage)) ?>">
                        <span class="glyphicon glyphicon-film"></span>&nbsp;<?php echo $this->translate('Movies').' V3' ?>
                    </a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li><a href="<?php echo $this->url('movies', array('lang' => $this->moviesLanguage)) ?>"><?php echo $this->translate('Home') ?></a></li>
                        <li><a href="<?php echo $this->url('movies', array('action'=>'advanced-search', 'lang' => $this->moviesLanguage)) ?>"><?php echo $this->translate('Advanced search'); ?></a></li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <li>
                            <?php
                                if(!$this->identity()){
                            ?>
                            <a href="<?= $this->url('auth', array('lang' => $this->moviesLanguage, 'action' => 'login'));?>">
                                <?php echo $this->translate('Login'); ?>
                            </a>
                            <?php
                                }
                                else{
                            ?>
                            <a href="<?= $this->url('auth', array('lang' => $this->moviesLanguage, 'action' => 'logout'));?>">
                                <?php echo $this->translate('Logout'); ?>
                            </a>
                            <?php
                                }
                            ?>
                        </li>
                        <?php
                            if($this->identity()){
                        ?>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown"> <?php echo $this->translate('Admin') ?> <span class="caret"></span></a>
                            <ul class="dropdown-menu" role="menu">
                                <li role="presentation" class="dropdown-header"><?php echo $this->translate('Medium') ?></li>
                                <li>
                                    <a href="<?php echo $this->url('admin', array('action'=>'add-movie', 'lang' => $this->moviesLanguage)) ?>"><?php echo $this->translate('add') ?></a>
                                </li>
                                <li>
                                    <a href="<?php echo $this->url('admin', array('action'=>'import-movie', 'lang' => $this->moviesLanguage)) ?>"><?php echo $this->translate('import') ?></a>
                                </li>
                                <li>
                                    <a href="<?php echo $this->url('admin', array('action'=>'export-movie', 'lang' => $this->moviesLanguage)) ?>"><?php echo $this->translate('export') ?></a>
                                </li>
                                <li class="divider"></li>
                                <li role="presentation" class="dropdown-header"><?php echo $this->translate('User') ?></li>
                                <li>
                                    <a href="<?php echo $this->url('admin', array('action'=>'add-user', 'lang' => $this->moviesLanguage)) ?>"><?php echo $this->translate('add') ?></a>
                                </li>
                                <li>
                                    <a href="<?php echo $this->url('admin', array('action'=>'list-user', 'lang' => $this->moviesLanguage)) ?>"><?php echo $this->translate('manage') ?></a>
                                </li>
                                <li class="divider"></li>
                                <li role="presentation" class="dropdown-header"><?php echo $this->translate('Page') ?></li>
                                <li>
                                    <a href="<?php echo $this->url('admin', array('action'=>'site-set-up', 'lang' => $this->moviesLanguage)) ?>"><?php echo $this->translate('set up') ?></a>
                                </li>
                            </ul>
                        </li>
                        <?php
                            }
                        ?>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown"> <?php echo $this->translate('Language'); ?> <span class="caret"></span></a>
                            <ul class="dropdown-menu" role="menu">
                                <li><a href="<?= $this->url($this->route, array('lang' => 'de', 'action' => $this->moviesAction, 'id' => $this->moviesId));?>">
                                    <?php echo $this->translate('German'); ?>
                                </a></li>
                                <li><a href="<?=$this->url($this->route, array('lang' => 'en', 'action' => $this->moviesAction, 'id' => $this->moviesId));?>">
                                    <?php echo $this->translate('English'); ?>
                                </a></li>
                            </ul>
                        </li>
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </nav>
        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>created by <a target="_blank" href="http://spezelechse.de/">Spezelechse</a>, published on <a target="_blank" href="https://github.com/Spezelechse/movies-v3">GitHub</a></p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
