<div class="zf-table-wrap  form-inline">
    <div class="table-header">
    </div>
    <div class="row ">
        <div class="col-sm-1 pull-left">
            <?php if(empty($this->name['disableShowAs'])){ ?>
            <label>
                <?php echo $this->name['translator']->translate('Show as').': '; ?>
                <select id="additionalParams" class="form-control">
                    <option value="list"><?php echo $this->name['translator']->translate('List'); ?></option>
                    <option value="detail"><?php echo $this->name['translator']->translate('Details'); ?></option>
                    <option value="pic"><?php echo $this->name['translator']->translate('Cover'); ?></option>
                </select>
            </label>
            <?php } ?>
        </div>
        <?php if ($this->showQuickSearch): ?>
            <div class="dataTables_filter pull-right col-sm-3" id="dataTable_filter">
                <label class="pull-right">
                    <?php echo $this->name['translator']->translate('Search'); ?>: <input type="text" aria-controls="dataTable" class="quick-search form-control" value="<?php echo $this->quickSearch ?>">
                </label>
            </div>
        <?php endif; ?>
    </div>
    <?php echo $this->table; ?>
    <div class="row">
        <div class="col-sm-6 text-left">
            <?php if ($this->showItemPerPage): ?>
                <label class="pull-left">
                    <select class="itemPerPage form-control">
                        <?php foreach ($this->itemCountPerPageValues as $item): ?>
                            <?php $selected = ($item == $this->itemCountPerPage) ? 'selected="selected"' : '""'; ?>
                            <option <?php echo $selected ?>><?php echo $item ?></option>
                        <?php endforeach; ?>
                    </select> 
                </label> 
           <?php endif; ?>
           <?php if($this->showExportToCSV): ?>
             <a href="#" style="margin-left: 10px;" class="export-csv">Export to CSV</a>
           <?php endif;?>
        </div>
        <div class="col-sm-6 text-right">
            <?php if ($this->showPagination): ?>
                <div class="dataTables_paginate paging_bootstrap pagination">
                    <?php echo $this->paginator; ?>
                </div>
            <?php endif; ?>
        </div>
        <div class="processing">
        </div>
    </div>
    <?php echo $this->paramsWrap; ?>
</div>
<script>
jQuery(document).ready(function($) {
    <?php
    if(isset($this->name['listStyle'])){
        ?>
    $("#additionalParams").val("<?php echo $this->name['listStyle']; ?>"); 
    <?php
        }
        ?>  
    $("#additionalParams").on('change', function(e){
        e.preventDefault();
        table();
    });
    
    function table(){
        $("#tableContainer").zfTable("<?php echo $this->name['path']; ?>", {
            sendAdditionalParams: function() {
                var data = $('#additionalParams').val();
                return '&listStyle=' + data;
            },
        });
    }
 });
</script>