<div class="zf-table-wrap  form-inline">
    <div class="table-header">
    </div>
    <div class="row ">
        <div class="col-sm-2 pull-left">
            <label>
                <?php echo $this->name['translator']->translate('Show as').': '; ?>
                <select id="additionalParams" class="form-control">
                    <option value="list"><?php echo $this->name['translator']->translate('List'); ?></option>
                    <option value="detail"><?php echo $this->name['translator']->translate('Details'); ?></option>
                    <option value="pic"><?php echo $this->name['translator']->translate('Cover'); ?></option>
                </select>
            </label>
        </div>
        <?php if ($this->showQuickSearch): ?>
            <div class="dataTables_filter pull-right col-sm-3" id="dataTable_filter">
                <label class="pull-right">
                    <?php echo $this->name['translator']->translate('Search'); ?>: <input type="text" aria-controls="dataTable" class="quick-search form-control" value="<?php echo $this->quickSearch ?>">
                </label>
            </div>
        <?php endif; ?>
    </div>
    
    <div class="content">
        <?php foreach($this->rows as $row):?>
        <div class="row" style="margin-bottom: 10px;">
            <div class="col-xs-12 col-sm-2">
                    <?php 
                        if($row['cover_file']!=''){ 
                    ?>  
                    <a href="<?php echo explode('"',$row['title'])[1]; ?>">
                        <img class="img-responsive" src="<?php echo $this->name['basicPath']; ?>img/cover/<?php echo $row['cover_file']; ?>">
                    </a>
                    <?php 
                    }
                    else{
                    ?>
                    <a href="<?php echo explode('"',$row['title'])[1]; ?>">
                        <img class="img-responsive" src="<?php echo $this->name['basicPath']; ?>img/cover/placeholder.png">
                    </a>
                    <?php
                    }
                    ?>
            </div>
            <div class="col-xs-12 col-sm-10">
                <h4>
                    <?php echo $row['title']?>
                    <small>
                        <?php 
                            if($row['dvd_or_bluray']==1){
                                echo "DVD";
                            }
                            else{
                                echo "Blu-ray";
                            }
                        ?>
                    </small>
                </h4>
                <div class="movie-list-detail-info">
                    <?php echo '<h5>'.$this->name['translator']->translate('Type').': <small>'.$row['type'].'</small></h5>'; ?>
                    <?php echo '<h5>'.$this->name['translator']->translate('Genre').': <small>'.$row['genres'].'</small></h5>'; ?>
                    <?php echo '<h5>'.$this->name['translator']->translate('Duration').': <small>'.$row['duration'].'</small></h5>'; ?>
                </div>
                <div class="hyphenless" style="margin-top: 10px;">
                    <h5>
                <?php
                    if(strlen($row['content'])>500){
                        echo substr($row['content'], 0, strpos($row['content'], ' ',500));
                        echo ' ...';
                    }
                    else{
                        echo $row['content'];
                    }
                ?>
                    </h5>
                </div>
                <br />
            </div>
        </div>
        <?php endforeach;?>
    </div>
    <div class="row">
        <div class="col-sm-6 text-left">
            <?php if ($this->showItemPerPage): ?>
                <label class="pull-left">
                    <select class="itemPerPage form-control">
                        <?php foreach ($this->itemCountPerPageValues as $item): ?>
                            <?php $selected = ($item == $this->itemCountPerPage) ? 'selected="selected"' : '""'; ?>
                            <option <?php echo $selected ?>><?php echo $item ?></option>
                        <?php endforeach; ?>
                    </select> 
                </label> 
           <?php endif; ?>
           <?php if($this->showExportToCSV): ?>
             <a href="#" style="margin-left: 10px;" class="export-csv">Export to CSV</a>
           <?php endif;?>
        </div>
        <div class="col-sm-6 text-right">
            <?php if ($this->showPagination): ?>
                <div class="dataTables_paginate paging_bootstrap pagination">
                    <?php echo $this->paginator; ?>
                </div>
            <?php endif; ?>
        </div>
        <div class="processing">
        </div>
    </div>
    <?php echo $this->paramsWrap;?>
</div>
<script>
jQuery(document).ready(function($) {
    <?php
    if(isset($this->name['listStyle'])){
        ?>
    $("#additionalParams").val("<?php echo $this->name['listStyle']; ?>"); 
    <?php
        }
        ?>  
    $("#additionalParams").on('change', function(e){
        e.preventDefault();
        table();
    });
    
    function table(){
        $("#tableContainer").zfTable("<?php echo $this->name['path']; ?>", {
            sendAdditionalParams: function() {
                var data = $('#additionalParams').val();
                return '&listStyle=' + data;
            },
        });
    }
 });
</script>