<div class="zf-table-wrap  form-inline">
    <div class="table-header">
    </div>
    <div class="row ">
        <div class="col-sm-2 pull-left">
            <label>
                <?php echo $this->name['translator']->translate('Show as').': '; ?>
                <select id="additionalParams" class="form-control">
                    <option value="list"><?php echo $this->name['translator']->translate('List'); ?></option>
                    <option value="detail"><?php echo $this->name['translator']->translate('Details'); ?></option>
                    <option value="pic"><?php echo $this->name['translator']->translate('Cover'); ?></option>
                </select>
            </label>
        </div>
        <?php if ($this->showQuickSearch): ?>
            <div class="dataTables_filter pull-right col-sm-4" id="dataTable_filter">
                <label class="pull-right">
                    <?php echo $this->name['translator']->translate('Search'); ?>: <input type="text" aria-controls="dataTable" class="quick-search form-control" value="<?php echo $this->quickSearch ?>">
                </label>
            </div>
        <?php endif; ?>
    </div>
    
    <div class="content">
        <div class="row">
        <?php foreach($this->rows as $row):?>
            <div class="hidden-xs col-sm-3 col-md-2" style="padding:0; margin:0; margin-bottom: 5px;">
                <div style="padding: 4px;">
                    <?php 
                        if($row['cover_file']!=''){
                    ?>  
                    <a href="<?php echo explode('"',$row['title'])[1]; ?>">
                        <div class="col-sm-12 movies-list-cover" style="background-image:url('<?php echo $this->name['basicPath']; ?>img/thumb/<?php echo $row['cover_file']; ?>');"></div>
                    </a>
                    <?php 
                    }
                    else{
                    ?>
                    <a href="<?php echo explode('"',$row['title'])[1]; ?>">
                        <div class="col-sm-12 movies-list-cover" style="background-image:url('<?php echo $this->name['basicPath']; ?>img/thumb/placeholder.png');"></div>
                    </a>
                    <?php
                    }
                    ?>
                </div>
            </div>
            <div class="visible-xs col-xs-12" style="padding:0; margin:0; margin-bottom: 5px;">
                <div>
                    <?php 
                        if($row['cover_file']!=''){ 
                    ?>  
                    <a href="<?php echo explode('"',$row['title'])[1]; ?>">
                        <img class="img-responsive" src="img/cover/<?php echo $row['cover_file']; ?>">
                    </a>
                    <?php 
                    }
                    else{
                    ?>
                    <a href="<?php echo explode('"',$row['title'])[1]; ?>">
                        <img class="img-responsive" src="img/cover/placeholder.png">
                    </a>
                    <?php
                    }
                    ?>
                </div>
            </div>
        <?php endforeach;?>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-6 text-left">
            <?php if ($this->showItemPerPage): ?>
                <label class="pull-left">
                    <select class="itemPerPage form-control">
                        <?php foreach ($this->itemCountPerPageValues as $item): ?>
                            <?php $selected = ($item == $this->itemCountPerPage) ? 'selected="selected"' : '""'; ?>
                            <option <?php echo $selected ?>><?php echo $item ?></option>
                        <?php endforeach; ?>
                    </select> 
                </label> 
           <?php endif; ?>
           <?php if($this->showExportToCSV): ?>
             <a href="#" style="margin-left: 10px;" class="export-csv">Export to CSV</a>
           <?php endif;?>
        </div>
        <div class="col-sm-6 text-right">
            <?php if ($this->showPagination): ?>
                <div class="dataTables_paginate paging_bootstrap pagination">
                    <?php echo $this->paginator; ?>
                </div>
            <?php endif; ?>
        </div>
        <div class="processing">
        </div>
    </div>
    <?php echo $this->paramsWrap;?>
</div>
<script>
jQuery(document).ready(function($) {
    <?php
    if(isset($this->name['listStyle'])){
        ?>
    $("#additionalParams").val("<?php echo $this->name['listStyle']; ?>"); 
    <?php
        }
        ?>  
    $("#additionalParams").on('change', function(e){
        e.preventDefault();
        table();
    });
    
    function table(){
        $("#tableContainer").zfTable("<?php echo $this->name['path']; ?>", {
            sendAdditionalParams: function() {
                var data = $('#additionalParams').val();
                return '&listStyle=' + data;
            },
        });
    }
 });
</script>