-- MySQL Script generated by MySQL Workbench
-- 07/25/14 16:34:03
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema movies_v3
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `BORROWER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BORROWER` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `USER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `USER` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(30) NOT NULL,
  `SURNAME` VARCHAR(30) NOT NULL,
  `USERNAME` VARCHAR(30) NOT NULL,
  `PASSWORD` VARCHAR(32) NOT NULL,
  `RIGHTS` BIT(7) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `USERNAME_UNIQUE` (`USERNAME` ASC),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TYPE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TYPE` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `COVER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `COVER` (
  `ID` INT NOT NULL,
  `NAME` VARCHAR(150) NOT NULL,
  `FILENAME` VARCHAR(150) NOT NULL,
  `SOURCE` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MEDIUM`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MEDIUM` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `TITLE` VARCHAR(150) NOT NULL,
  `BORROWER_ID` INT NULL,
  `TYPE_ID` INT NULL,
  `OWNER_ID` INT NOT NULL,
  `COVER_ID` INT NULL,
  `DURATION` INT NULL,
  `FSK` INT NULL,
  `PREMIERE` DATE NULL,
  `NUM_DISKS` INT NULL,
  `CONTENT` TEXT NULL,
  `BORROWED` TINYINT NULL,
  `DVD_OR_BLURAY` TINYINT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC),
  INDEX `fk_MEDIUM_BORROWER1_idx` (`BORROWER_ID` ASC),
  INDEX `fk_MEDIUM_USER1_idx` (`OWNER_ID` ASC),
  INDEX `fk_MEDIUM_TYPE1_idx` (`TYPE_ID` ASC),
  INDEX `fk_MEDIUM_COVER1_idx` (`COVER_ID` ASC),
  CONSTRAINT `fk_MEDIUM_BORROWER1`
    FOREIGN KEY (`BORROWER_ID`)
    REFERENCES `BORROWER` (`ID`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MEDIUM_USER1`
    FOREIGN KEY (`OWNER_ID`)
    REFERENCES `USER` (`ID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MEDIUM_TYPE1`
    FOREIGN KEY (`TYPE_ID`)
    REFERENCES `TYPE` (`ID`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MEDIUM_COVER1`
    FOREIGN KEY (`COVER_ID`)
    REFERENCES `COVER` (`ID`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DIRECTOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DIRECTOR` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MEDIUM_has_DIRECTOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MEDIUM_has_DIRECTOR` (
  `MEDIUM_ID` INT NOT NULL,
  `DIRECTOR_ID` INT NOT NULL,
  PRIMARY KEY (`MEDIUM_ID`, `DIRECTOR_ID`),
  INDEX `fk_MEDIUM_has_DIRECTOR_DIRECTOR1_idx` (`DIRECTOR_ID` ASC),
  INDEX `fk_MEDIUM_has_DIRECTOR_MEDIUM_idx` (`MEDIUM_ID` ASC),
  CONSTRAINT `fk_MEDIUM_has_DIRECTOR_MEDIUM`
    FOREIGN KEY (`MEDIUM_ID`)
    REFERENCES `MEDIUM` (`ID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MEDIUM_has_DIRECTOR_DIRECTOR1`
    FOREIGN KEY (`DIRECTOR_ID`)
    REFERENCES `DIRECTOR` (`ID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ACTOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ACTOR` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GENRE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GENRE` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PUBLISHER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PUBLISHER` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BLACKLIST`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BLACKLIST` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `TIME` TIMESTAMP NOT NULL,
  `IP` VARCHAR(15) NOT NULL,
  `TRY` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MEDIUM_has_GENRE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MEDIUM_has_GENRE` (
  `MEDIUM_ID` INT NOT NULL,
  `GENRE_ID` INT NOT NULL,
  PRIMARY KEY (`MEDIUM_ID`, `GENRE_ID`),
  INDEX `fk_MEDIUM_has_GENRE_GENRE1_idx` (`GENRE_ID` ASC),
  INDEX `fk_MEDIUM_has_GENRE_MEDIUM1_idx` (`MEDIUM_ID` ASC),
  CONSTRAINT `fk_MEDIUM_has_GENRE_MEDIUM1`
    FOREIGN KEY (`MEDIUM_ID`)
    REFERENCES `MEDIUM` (`ID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MEDIUM_has_GENRE_GENRE1`
    FOREIGN KEY (`GENRE_ID`)
    REFERENCES `GENRE` (`ID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MEDIUM_has_PUBLISHER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MEDIUM_has_PUBLISHER` (
  `MEDIUM_ID` INT NOT NULL,
  `PUBLISHER_ID` INT NOT NULL,
  PRIMARY KEY (`MEDIUM_ID`, `PUBLISHER_ID`),
  INDEX `fk_MEDIUM_has_PUBLISHER_PUBLISHER1_idx` (`PUBLISHER_ID` ASC),
  INDEX `fk_MEDIUM_has_PUBLISHER_MEDIUM1_idx` (`MEDIUM_ID` ASC),
  CONSTRAINT `fk_MEDIUM_has_PUBLISHER_MEDIUM1`
    FOREIGN KEY (`MEDIUM_ID`)
    REFERENCES `MEDIUM` (`ID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MEDIUM_has_PUBLISHER_PUBLISHER1`
    FOREIGN KEY (`PUBLISHER_ID`)
    REFERENCES `PUBLISHER` (`ID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MEDIUM_has_ACTOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MEDIUM_has_ACTOR` (
  `MEDIUM_ID` INT NOT NULL,
  `ACTOR_ID` INT NOT NULL,
  `ROLE` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`MEDIUM_ID`, `ACTOR_ID`),
  INDEX `fk_MEDIUM_has_ACTOR_ACTOR1_idx` (`ACTOR_ID` ASC),
  INDEX `fk_MEDIUM_has_ACTOR_MEDIUM1_idx` (`MEDIUM_ID` ASC),
  CONSTRAINT `fk_MEDIUM_has_ACTOR_MEDIUM1`
    FOREIGN KEY (`MEDIUM_ID`)
    REFERENCES `MEDIUM` (`ID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MEDIUM_has_ACTOR_ACTOR1`
    FOREIGN KEY (`ACTOR_ID`)
    REFERENCES `ACTOR` (`ID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
