<?php
/**
 * @package Movies
 */
$escaper = new Zend\Escaper\Escaper('utf-8');
// Template
?>
<h3>
	<?php echo $this->translate('Search results for:'); ?>
	<br>
	<small>
		<?php echo $this->translate('Publisher').' = '.$escaper->escapeHtml($search_value_text); ?>
	</small>
</h3>

<div id="tableContainer"></div>
<script>
    $("#tableContainer").zfTable("<?php echo $this->url('search', array('action'=>'ajax-publisher', 'value'=> $search_value,'lang'=>$this->language)); ?>");
</script>