<?php
/**
 * @package Movies
 */

echo $this->messageHelper($this->flashMessenger());

// Template
$form = $this->form;
$form->setAttribute('action', $this->url('admin', array('lang' => $language,'action' => 'add-medium')));
$form->setAttribute('role', 'form');
$form->setAttribute('class', 'form-horizontal');
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('csrf'));
?>
<div class="row">
	<div class="col-xs-12 col-sm-9 movies-data-left">
		<div class="movies-data-content-wrapper">
			<div class="movies-data-title">
				<div class="row">
					<div class="col-sm-2 pull-left">
						<h4><?php echo $this->translate('Title'); ?></h4>
					</div>
					<div class="col-sm-2 pull-right">
						<button type="button" class="btn btn-xs" data-toggle="modal" data-target="#imdbModal" style="margin-top:5px;" id="imdb-import">
						<?php echo $this->translate('IMDb import'); ?>
						</button>
					</div>
				</div>
				<div class="form-group">
					<?php echo $this->formLabel($form->get('title_de')); ?>
					<div class="col-sm-10">
						<?php echo $this->formElement($form->get('title_de')); ?>
					</div>
				</div>
				<div class="form-group">
					<?php echo $this->formLabel($form->get('title_en')); ?>
					<div class="col-sm-10">
						<?php echo $this->formElement($form->get('title_en')); ?>
					</div>
				</div>
			</div>
			<div class="movies-data-content">
				<div><h4><?php echo $this->translate('Content'); ?></h4></div>
				<div class="form-group">
					<?php echo $this->formLabel($form->get('content_de')); ?>
					<div class="col-sm-10">
						<?php echo $this->formElement($form->get('content_de')); ?>
					</div>
				</div>
				<div class="form-group">
					<?php echo $this->formLabel($form->get('content_en')); ?>
					<div class="col-sm-10">
						<?php echo $this->formElement($form->get('content_en')); ?>
					</div>
				</div>
			</div>
		</div>
		<div class="col-xs-0 col-sm-2"></div>
		<div class="col-xs-12 col-sm-8 movies-data-actor">
			<table class="table table-striped table-hover">
				<tr style="">
					<th class="col-xs-6 col-sm-6" style="background-color: #FFF;"><?php echo $this->formLabel($form->get('actors_text')); ?></th>
					<th class="col-xs-6 col-sm-6"><?php echo $this->formLabel($form->get('roles_text')); ?></th>
				</tr>
				<tr>
					<td><?php echo $this->formElement($form->get('actors_text')); ?></td>
					<td><?php echo $this->formElement($form->get('roles_text')); ?></td>
				</tr>
			</table>
		</div>
		<div class="col-xs-0 col-sm-2"></div>
	</div>
	<div class="col-xs-12 col-sm-3 movies-data-right">
		<div class="movies-data-cover">
			<img class="img-responsive" src="<?php echo $this->url('movies'); ?>img/cover/placeholder.png">
			<div class="movies-data-cover-info">
				<div class="form-group">
					<div class="col-sm-12 movies-cover-file">
						<?php echo $this->formFile($form->get('cover_file')); ?>
					</div>
				</div>
				<div class="form-group">
					<?php echo $this->formLabel($form->get('cover_source')); ?>
					<div class="col-sm-8">
						<?php echo $this->formElement($form->get('cover_source')); ?>
					</div>
				</div>
			</div>
		</div>
		<div class="movies-data-info">
			<div id="genre-container" class="form-group">
				<div class="col-sm-4" style="padding:0;">
					<?php echo $this->formLabel($form->get('genre')); ?>
					<div class="col-sm-12 control-label add-container">
						<button type="button" class="btn btn-xs add-popover-multilingual" id="add-genre" data-selectid="genre-select" data-title="<?php echo $this->translate('Add new genre'); ?>" data-ajaxurl="<?php echo $this->url('admin', array('lang' => $language,'action' => 'add-genre-ajax'));?>">
						+
						</button>
					</div>
				</div>
				<div class="col-sm-8">
					<?php echo $this->formElement($form->get('genre')); ?>
				</div>
			</div>
			<div class="form-group">
				<div class="col-sm-4" style="padding:0;">
					<?php echo $this->formLabel($form->get('director')); ?>
					<div class="col-sm-12 control-label add-container">
						<button type="button" class="btn btn-xs add-popover" id="add-director" data-selectid="director-select" data-title="<?php echo $this->translate('Add new director'); ?>" data-ajaxurl="<?php echo $this->url('admin', array('lang' => $language,'action' => 'add-director-ajax'));?>">
						+
						</button>
					</div>
				</div>
				<div class="col-sm-8">
					<?php echo $this->formElement($form->get('director')); ?>
				</div>
			</div>
			<div class="form-group">
				<div class="col-sm-4" style="padding:0;">
					<?php echo $this->formLabel($form->get('publisher')); ?>
					<div class="col-sm-12 control-label add-container">
						<button type="button" class="btn btn-xs add-popover" id="add-publisher" data-selectid="publisher-select" data-title="<?php echo $this->translate('Add new publisher'); ?>" data-ajaxurl="<?php echo $this->url('admin', array('lang' => $language,'action' => 'add-publisher-ajax'));?>">
						+
						</button>
					</div>
				</div>
				<div class="col-sm-8">
					<?php echo $this->formElement($form->get('publisher')); ?>
				</div>
			</div>
			<div class="form-group">
				<div class="col-sm-4" style="padding:0;">
					<?php echo $this->formLabel($form->get('type_id')); ?>
					<div class="col-sm-12 control-label add-container">
						<button type="button" class="btn btn-xs add-popover-multilingual" id="add-type" data-selectid="type-select" data-title="<?php echo $this->translate('Add new type'); ?>" data-ajaxurl="<?php echo $this->url('admin', array('lang' => $language,'action' => 'add-type-ajax'));?>">
						+
						</button>
					</div>
				</div>
				<div class="col-sm-8">
					<?php echo $this->formElement($form->get('type_id')); ?>
				</div>
			</div>
			<div class="form-group">
				<?php echo $this->formLabel($form->get('owner_id')); ?>
				<div class="col-sm-8">
					<?php echo $this->formElement($form->get('owner_id')); ?>
				</div>
			</div>
			<div class="form-group">
				<?php echo $this->formLabel($form->get('duration')); ?>
				<div class="col-sm-8">
					<?php echo $this->formElement($form->get('duration')); ?>
				</div>
			</div>
			<div class="form-group">
				<?php echo $this->formLabel($form->get('fsk')); ?>
				<div class="col-sm-8">
					<?php echo $this->formSelect($form->get('fsk')); ?>
				</div>
			</div>
			<div class="form-group">
				<?php echo $this->formLabel($form->get('premiere')); ?>
				<div class="col-sm-8">
					<?php echo $this->formElement($form->get('premiere')); ?>
				</div>
			</div>
			<div class="form-group">
				<?php echo $this->formLabel($form->get('num_disks')); ?>
				<div class="col-sm-8">
					<?php echo $this->formElement($form->get('num_disks')); ?>
				</div>
			</div>
			<div class="form-group">
				<?php echo $this->formLabel($form->get('dvd_or_bluray')); ?>
				<div class="col-sm-8">
					<?php echo $this->formElement($form->get('dvd_or_bluray')); ?>
				</div>
			</div>
			<div class="form-group">
				<?php echo $this->formLabel($form->get('imdb_url')); ?>
				<div class="col-sm-8">
					<?php echo $this->formElement($form->get('imdb_url')); ?>
				</div>
			</div>
		</div>
	</div>
</div>
<div class="row text-center">
	<div class="form-group">
			<?php echo $this->formSubmit($form->get('submit')); ?>
	</div>
</div>
<?php echo $this->form()->closeTag(); ?>

<script type="text/javascript">
$(function() {
	$( "#premiere" ).datepicker({ dateFormat: "yy-mm-dd" });
});
</script>

<script type="text/javascript" src="/moviesv3/js/movies/popover.js"></script> 

<script type="text/javascript" src="/moviesv3/js/movies/imdb.js"></script> 

<div id="popover-content-multilingual" class="hide">
	<div class="form-group">
		<label>de: <input class="de-input" name="de-input" type="text" value=""></label>
	</div>
	<div class="form-group">
		<label>en: <input class="en-input" name="en-input" type="text" value=""></label>
    </div>
    <button class="btn btn-primary pop-add">add</button>
    <button class="btn btn-danger pop-close">close</button>
</div>
<div id="popover-content" class="hide">
	<div class="form-group">
		<input class="input" name="input" type="text" value="">
	</div>
    <button class="btn btn-primary pop-add">add</button>
    <button class="btn btn-danger pop-close">close</button>     
</div>

<div class="modal fade" id="imdbModal" tabindex="-1" role="dialog" data-baseurl="<?php echo $this->url('imdb', array('lang' => $language));?>" aria-labelledby="imdbModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close imdb-close-action" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="myModalLabel"><?php echo $this->translate('IMDb import'); ?></h4>
      </div>
      <div class="modal-search row">  	
		<div class="form-group">
			<div class="col-xs-0 col-sm-2">
			</div>
			<div class="col-sm-6">
				<input type="text" class="form-control" id="imdb-search">
			</div>
			<div class="col-sm-2">
				<button class="btn btn-default" id="imdb-search-action"><?php echo $this->translate('Search');?></button>
			</div>
			<div class="col-xs-0 col-sm-2">
			</div>
		</div>
      </div>
      <div class="modal-body text-center row">
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default imdb-close-action" data-dismiss="modal"><?php echo $this->translate('Close');?></button>
        <button type="button" class="btn btn-default" data-dismiss="modal"><?php echo $this->translate('Hide');?></button>
        <button type="button" class="btn btn-primary" id="imdb-import-action"><?php echo $this->translate('Import'); ?></button>
      </div>
    </div>
  </div>
</div>