<?php
/**
 * @package Movies
 */

$escaper = new Zend\Escaper\Escaper('utf-8');
// Template
?>
<div class="row">
	<div class="col-xs-12 col-sm-9 movies-data-left">
		<div class="movies-data-content-wrapper">
			<div class="text-right movies-data-edit">
				<a href="<?php echo $this->url('admin', array('action'=>'edit-movie','lang'=>$this->language, 'id'=>$medium->id)); ?>"><button type="button" class="btn btn-success btn-xs"><span class="glyphicon glyphicon-pencil"></span></button></a>
				<a href="<?php echo $this->url('admin', array('action'=>'delete-movie','lang'=>$this->language, 'id'=>$medium->id)); ?>"><button type="button" class="btn btn-danger btn-xs"><span class="glyphicon glyphicon-remove"></span></button></a>
			</div>
			<div class="movies-data-title">
				<h2><?php echo $escaper->escapeHtml($medium->getTitle($this->language)); ?>
					<small>
						<?php
							echo '(';
							if($medium->num_disks>1){
								echo $escaper->escapeHtml($medium->num_disks);
								echo ' ';
							}
							if($medium->dvd_or_bluray==0){
								echo 'DVD';
							}
							else{
								echo 'Blu-ray';
							}
							echo ')';
						?>
					</small>
				</h2>
			</div>
			<div class="movies-data-content hyphenless">
				<?php echo $escaper->escapeHtml($medium->getContent($this->language)); ?>
			</div>
		</div>
		<div class="col-xs-0 col-sm-2"></div>
		<div class="col-xs-12 col-sm-8 movies-data-actor">
			<table class="table table-striped table-hover">
				<tr style="">
					<th class="col-xs-6 col-sm-6" style="background-color: #FFF;"><?php echo $this->translate('Actor'); ?></th>
					<th class="col-xs-6 col-sm-6"><?php echo $this->translate('Role'); ?></th>
				</tr>
			<?php
				if($medium->actors->count()>0){
					foreach ($medium->actors as $actor) {
						echo '<tr>';
						echo '<td>'.$escaper->escapeHtml($actor->name).'</td>';
						echo '<td>'.$escaper->escapeHtml($actor->role).'</td>';
						echo '</tr>';
					}
				}
				else{
					?>
				<tr>
					<td>-</td>
					<td>-</td>
				</tr>
					<?php
				}
			?>
			</table>
		</div>
		<div class="col-xs-0 col-sm-2"></div>
	</div>
	<div class="col-xs-12 col-sm-3 movies-data-right">
		<div class="movies-data-cover">
			<img class="img-responsive" src="<?php echo $this->url('movies'); ?>img/cover/<?php echo $medium->getCover(); ?>">
			<?php if(isset($medium->cover_source)){ ?>
			<div class="col-sm-12 text-center">
				<?php echo $this->translate('Source') ?>: <a href="<?php echo $escaper->escapeHtml($medium->getCoverSource()); ?>" target="_blank"><?php echo $escaper->escapeHtml($medium->getCoverSourceDomain()); ?></a>
			</div>
			<?php } ?>
		</div>
		<div class="movies-data-info">
			<h5><?php echo $this->translate('Genre'); ?>: 
				<small>
				<?php
					$genres='';
					foreach($medium->genre as $genre)
					{
						$genres.=$genre->getName($this->language).', ';
					}
					echo ($genres!='') ? $escaper->escapeHtml(substr($genres, 0, strlen($genres)-2)) : '-';
				?>
				</small>
			</h5>
			<h5><?php echo $this->translate('Director'); ?>: 
				<small>
				<?php
					$directors='';
					foreach($medium->director as $director)
					{
						$directors.=$director->name.', ';
					}
					echo ($directors!='') ? $escaper->escapeHtml(substr($directors, 0, strlen($directors)-2)) : '-';
				?>
				</small>
			</h5>
			<h5><?php echo $this->translate('Publisher'); ?>: 
				<small>
				<?php
					$publishers='';
					foreach($medium->publisher as $publisher)
					{
						$publishers.=$publisher->name.', ';
					}
					echo ($publishers!='') ? $escaper->escapeHtml(substr($publishers, 0, strlen($publishers)-2)) : '-';
				?>
				</small>
			</h5>
			<h5><?php echo $this->translate('Type'); ?>: 
				<small>
				<?php
					echo (!empty($medium->type)) ? $escaper->escapeHtml($medium->type->getName($this->language)) : '-';
				?>
				</small>
			</h5>
			<h5><?php echo $this->translate('Owner'); ?>: 
				<small>
				<?php
					echo (!empty($medium->owner)) ? $escaper->escapeHtml($medium->owner->username) : '-';
				?>
				</small>
			</h5>
			<h5><?php echo $this->translate('Duration'); ?>: 
				<small>
				<?php
					echo (!empty($medium->duration)) ? $escaper->escapeHtml($medium->duration).' min.' : '-';
				?>
				</small>
			</h5>
			<h5><?php echo $this->translate('FSK'); ?>: 
				<small>
				<?php
					echo (!empty($medium->fsk)) ? $escaper->escapeHtml($medium->fsk) : '-';
				?>
				</small>
			</h5>
			<h5><?php echo $this->translate('Premiere'); ?>: 
				<small>
				<?php
					echo (!empty($medium->premiere)) ? $escaper->escapeHtml($medium->premiere) : '-';
				?>
				</small>
			</h5>
		</div>
	</div>
</div>