<?php
/**
 * @package Movies
 */

use Zend\Crypt\Password\Bcrypt;

// Template
echo $this->messageHelper($this->flashMessenger());

$form = $this->form;
$form->setAttribute('action', $this->url('auth', array('lang' => $language,'action' => 'auth')));
$form->setAttribute('role', 'form');
$form->setAttribute('class', 'form-horizontal');
$form->prepare();
?>

<div class="row">
	<div class="col-xs-0 col-sm-3"></div>
	<div class="col-xs-12 col-sm-6">
		<?php
		echo $this->form()->openTag($form);
		?>
		<div class="form-group">
			<?php echo $this->formLabel($form->get('username')); ?>
			<div class="col-sm-8">
				<?php echo $this->formElement($form->get('username')); ?>
			</div>
		</div>
		<div class="form-group">
			<?php echo $this->formLabel($form->get('password')); ?>
			<div class="col-sm-8">
				<?php echo $this->formElement($form->get('password')); ?>
			</div>
		</div>
		<div class="form-group">
			<div class="col-sm-offset-2 col-sm-10">
				<div class="col-sm-1">
					<div class="checkbox">
					<?php echo $this->formElement($form->get('remember')); ?>
					</div>
				</div>
				<?php echo $this->formLabel($form->get('remember')); ?>
			</div>
		</div>
		<div class="form-group">
			<div class="col-sm-offset-2 col-sm-8">
				<?php echo $this->formSubmit($form->get('submit')); ?>
			</div>
		</div>
	<?php echo $this->form()->closeTag(); ?>
	</div>
	<div class="col-xs-0 col-sm-3"></div>
</div>