<?php
/**
 * @package Movies
 */
$missing='';
if(!empty($director_missing)){
	$missing.="<h5>".$this->translate('Director').":";
	foreach ($director_missing as $value) {
		$missing.="<small>";
		$missing.=$value;
		$missing.="</small>";
	}
	$missing.="<h5>";
}
if(!empty($publisher_missing)){
	$missing.="<h5>".$this->translate('Publisher').":";
	foreach ($publisher_missing as $value) {
		$missing.="<small>";
		$missing.=$value;
		$missing.="</small>";
	}
	$missing.="<h5>";
}
if(!empty($genre_missing)){
	$missing.="<h5>".$this->translate('Genre').":";
	foreach ($genre_missing as $value) {
		$missing.="<small>";
		$missing.=$value;
		$missing.="</small>";
	}
	$missing.="<h5>";
}
if(!empty($type_id_missing)){
	$missing.="<h5>".$this->translate('Type').":";
	$missing.="<small>";
	$missing.=$value;
	$missing.="</small>";
	$missing.="<h5>";
}

if($missing!=''){
echo '<div class="col-sm-12 pull-left text-left movies-missing-values">';
echo "<h5>".$this->translate('The following values are missing and have to be added manually:')."<h5>";
echo $missing;
echo '</div>';
}
?>